import subprocess as sb
import os
import datetime

class render_povray():
    def __init__(self,infile,outfile,paksize,tilesize_x=1,tilesize_y=1,tilesize_z=1,winter=0,make_front=0,pakstr="pak128japan"):
        self.infile=infile
        self.outfile=outfile
        self.paksize=int(paksize)
        self.Nx=int(tilesize_x)
        self.Ny=int(tilesize_y)
        self.Nz=int(tilesize_z)
        self.winter=int(winter)
        self.make_front=int(make_front)
        self.pakstr=pakstr
    def flag(self):
        def declare_povray(param,input_str):
            return "#declare "+str(param)+"="+str(input_str)+";\n"
        if self.paksize%4==0:
            # filesize define
            Width=self.paksize*(max(self.Nx,self.Ny))*4
            Height=self.paksize*(max(self.Nx,self.Ny,self.Nz//2))*9
            # make inc file which defines some values. 
            temp_inc_filepath=os.path.dirname(self.infile)+"/temp.inc"
            with open(temp_inc_filepath,mode="w") as f:
                f.write(declare_povray("int_x",self.Nx))
                f.write(declare_povray("int_y",self.Ny))
                f.write(declare_povray("int_z",max(self.Nz,1)))
                f.write(declare_povray("number_width",max(self.Nx,self.Ny)))
                f.write(declare_povray("number_hight",9))
                f.write(declare_povray("winter",self.winter))
                f.write(declare_povray("make_front_image",self.make_front))
                f.write(declare_povray("pak_str",'"'+self.pakstr+'"'))
            # rendering
            outname=self.outfile[:-4]
            if outname=="":
                outname=self.infile[:-4]
            if self.winter==1:
                outname+="-winter"
            try:
                sb.run(["pvengine.exe","/NR","/EXIT","/RENDER",str(self.infile),"Width="+str(Width),"Height="+str(Height),"Antialias=Off","+O"+outname])
            except:
                try:
                    sb.run(["povray",str(self.infile),"Width="+str(Width),"Height="+str(Height),"Antialias=Off","+O"+outname])
                except:
                    return False
            if os.path.isfile(outname+".png")==False:
                return False
            elif os.path.isfile(outname+"_0.png"):
                t_1=os.path.getmtime(outname+".png")
                t_2=os.path.getmtime(outname+"_0.png")
                if (t_1<t_2):
                    return False
                else:
                    return True
            else:
                return True
        else:
            return False

class povray_template():
    def __init__(self,outfile):
        self.outfile=outfile
    def write_snow(self,out):
        snow_outfile=os.path.dirname(out)+"/snow.inc"
        with open(snow_outfile,mode="w") as f:
            f.write("#declare winter_light=\n")
            f.write("light_source {\n\t<0,173,0>\n\tcolor rgb 33\n\tparallel\n\tpoint_at<0,0,0>\n}\n")
        return
    def write_file(self,out):
        with open(out,mode="w") as f:
            f.write('#include "snow.inc"\n')
            f.write('#include "temp.inc"\n')
            f.write('\n')
            f.write('// ---add include files---\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('// -----------------------\n')
            f.write('\n')
            f.write('// The default tile scale in this pov-ray file (not for pak file)\n')
            f.write('\n')
            f.write('#local paksize=64;\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('// ---camera setting---\n')
            f.write('\n')
            f.write('camera {\n')
            f.write('\torthographic\n')
            f.write('\tlocation <100,81.64965809277,100>*number_hight*paksize\n')
            f.write('\tlook_at <0,0.5,0>*paksize/128\n')
            f.write('\tright<1,0,-1> *paksize*number_width*2\n')
            f.write('\tup<1,0,1>  *paksize*number_hight/2\n')
            f.write('\t}\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('// ---light setting---\n')
            f.write('\n')
            f.write('light_source {\n')
            f.write('\t<0,173,100>*1000\n')
            f.write('\tcolor rgb 1\n')
            f.write('\tparallel\n')
            f.write('\tpoint_at<0,0,0>\n')
            f.write('}\n')
            f.write('// If winter==1, set a light to make the snow cover.\n')
            f.write('#if(winter)\n')
            f.write('\tlight_source{winter_light}\n')
            f.write('#end\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('// ----------------------------------\n')
            f.write('\n')
            f.write('//\n')
            f.write('\n')
            f.write('// the name of the object with all objects merged must be "obj"\n')
            f.write('\n')
            f.write('//\n')
            f.write('\n')
            f.write('// ---make objects below this line---\n')
            f.write('\n')
            f.write('#declare obj_end=\n')
            f.write('\n')
            f.write('#declare obj_straight=\n')
            f.write('\n')
            f.write('#declare obj_bend=\n')
            f.write('\n')
            f.write('#declare obj_diagonal=\n')
            f.write('\n')
            f.write('#declare obj_up=\n')
            f.write('\n')
            f.write('#declare obj_up2=\n')
            f.write('\n')
            f.write('#declare obj_all=\n')
            f.write('\n')
            f.write('#declare obj_T=\n')
            f.write('\n')
            f.write('#declare obj_T1=\n')
            f.write('\n')
            f.write('#declare obj_T2=\n')
            f.write('\n')
            f.write('#declare obj_single=\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('\n')
            f.write('// ---make objects above this line---\n')
            f.write('\n')
            f.write('// ---cut for diagonal---\n')
            f.write('#declare cut_box=object{box{<0-.00011,-paksize/4,0-.00011>,<paksize/2+0.00011,paksize/2,paksize/2+0.00011>}}')
            f.write('\n')
            f.write('// ---set objects---\n')
            f.write('#declare output_obj=obj_end\n')
            f.write('object{merge{\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*3/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\tscale<1,1,-1>}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*1/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\ttranslate<0,0,-1>*paksize/4\n')
            f.write('\t\tscale<1,1,-1>\n')
            f.write('\t\ttranslate<0,0,1>*paksize/4\n')
            f.write('\t}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-1)/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\ttranslate<0,0,-1>*paksize/4\n')
            f.write('\t\tscale<1,1,-1>\n')
            f.write('\t\ttranslate<0,0,1>*paksize/4\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\tscale<1,1,-1>\n')
            f.write('\t}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-3)/4\n')
            f.write('\t}}\n')
            f.write('\tscale<1,.8165,1> // To set 1 distance of y direction as 1px, rescaling the hight\n')
            f.write('\ttranslate<1,0,1>*paksize*(-4)\n')
            f.write('}\n')
            f.write('\n')
            f.write('#declare output_obj=obj_bend\n')
            f.write('object{merge{\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*3/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\ttranslate<0,0,1>*paksize*int_x/2}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*1/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\ttranslate<0,0,-1>*paksize*int_y/4\n')
            f.write('\t\ttranslate<1,0,0>*paksize*int_x/4\n')
            f.write('\t}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-1)/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\ttranslate<0,0,1>*paksize*int_y/2\n')
            f.write('\t\ttranslate<-1,0,-1>*paksize*int_y/4\n')
            f.write('\t}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-3)/4\n')
            f.write('\t}}\n')
            f.write('\tscale<1,.8165,1> // To set 1 distance of y direction as 1px, rescaling the hight\n')
            f.write('\ttranslate<1,0,1>*paksize*(-3)\n')
            f.write('}\n')
            f.write('\n')
            f.write('#declare output_obj=obj_straight\n')
            f.write('object{merge{\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*3/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\tscale<1,1,-1>}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*1/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{\n')
            f.write('\t\tobj_single\n')
            f.write('\t}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-1)/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{\n')
            f.write('\t\tobj_all\n')
            f.write('\t}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-3)/4\n')
            f.write('\t}}\n')
            f.write('\tscale<1,.8165,1> // To set 1 distance of y direction as 1px, rescaling the hight\n')
            f.write('\ttranslate<1,0,1>*paksize*(-2)\n')
            f.write('}\n')
            f.write('\n')
            f.write('#declare output_obj=obj_up\n')
            f.write('object{merge{\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*3/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\tscale<1,1,-1>}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*1/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\ttranslate<0,0,-1>*paksize/4\n')
            f.write('\t\tscale<1,1,-1>\n')
            f.write('\t\ttranslate<0,0,1>*paksize/4\n')
            f.write('\t}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-1)/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\ttranslate<0,0,-1>*paksize/4\n')
            f.write('\t\tscale<1,1,-1>\n')
            f.write('\t\ttranslate<0,0,1>*paksize/4\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\tscale<1,1,-1>\n')
            f.write('\t}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-3)/4\n')
            f.write('\t}}\n')
            f.write('\tscale<1,.8165,1> // To set 1 distance of y direction as 1px, rescaling the hight\n')
            f.write('\ttranslate<1,0,1>*paksize*(-1)\n')
            f.write('}\n')
            f.write('\n')
            f.write('#declare output_obj=obj_up2\n')
            f.write('object{merge{\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*3/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\tscale<1,1,-1>}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*1/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\ttranslate<0,0,-1>*paksize/4\n')
            f.write('\t\tscale<1,1,-1>\n')
            f.write('\t\ttranslate<0,0,1>*paksize/4\n')
            f.write('\t}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-1)/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\ttranslate<0,0,-1>*paksize/4\n')
            f.write('\t\tscale<1,1,-1>\n')
            f.write('\t\ttranslate<0,0,1>*paksize/4\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\tscale<1,1,-1>\n')
            f.write('\t}\n')
            f.write('\t}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-3)/4\n')
            f.write('\t}}\n')
            f.write('\tscale<1,.8165,1> // To set 1 distance of y direction as 1px, rescaling the hight\n')
            f.write('\ttranslate<1,0,1>*paksize*(0)\n')
            f.write('}\n')
            f.write('\n')
            f.write('#declare output_obj=obj_diagonal\n')
            f.write('object{merge{\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*3/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\ttranslate<0,0,1>*paksize*int_x/2}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*1/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\ttranslate<0,0,-1>*paksize*int_y/4\n')
            f.write('\t\ttranslate<1,0,0>*paksize*int_x/4\n')
            f.write('\t}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-1)/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\ttranslate<0,0,1>*paksize*int_y/2\n')
            f.write('\t\ttranslate<-1,0,-1>*paksize*int_y/4\n')
            f.write('\t}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-3)/4\n')
            f.write('\t}}\n')
            f.write('\tscale<1,.8165,1> // To set 1 distance of y direction as 1px, rescaling the hight\n')
            f.write('\ttranslate<1,0,1>*paksize*(1)\n')
            f.write('}\n')
            f.write('\n')
            f.write('\n')
            f.write('#declare output_obj=obj_T\n')
            f.write('object{merge{\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*3/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\ttranslate<0,0,1>*paksize*int_x/2}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*1/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,180,0>\n')
            f.write('\t\ttranslate<0,0,1>*paksize*int_y/2\n')
            f.write('\t\ttranslate<1,0,0>*paksize*int_x/2\n')
            f.write('\t}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-1)/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,270,0>\n')
            f.write('\t\ttranslate<1,0,0>*paksize*int_y/2\n')
            f.write('\t}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-3)/4\n')
            f.write('\t}}\n')
            f.write('\tscale<1,.8165,1> // To set 1 distance of y direction as 1px, rescaling the hight\n')
            f.write('\ttranslate<1,0,1>*paksize*(2)\n')
            f.write('}\n')
            f.write('\n')
            f.write('\n')
            f.write('#declare output_obj=obj_T1\n')
            f.write('object{merge{\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*3/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\ttranslate<0,0,1>*paksize*int_x/2}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*1/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,180,0>\n')
            f.write('\t\ttranslate<0,0,1>*paksize*int_y/2\n')
            f.write('\t\ttranslate<1,0,0>*paksize*int_x/2\n')
            f.write('\t}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-1)/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,270,0>\n')
            f.write('\t\ttranslate<1,0,0>*paksize*int_y/2\n')
            f.write('\t}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-3)/4\n')
            f.write('\t}}\n')
            f.write('\tscale<1,.8165,1> // To set 1 distance of y direction as 1px, rescaling the hight\n')
            f.write('\ttranslate<1,0,1>*paksize*(2)\n')
            f.write('}\n')
            f.write('\n')
            f.write('\n')
            f.write('#declare output_obj=obj_T2\n')
            f.write('object{merge{\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*3/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,90,0>\n')
            f.write('\t\ttranslate<0,0,1>*paksize*int_x/2}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*1/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,180,0>\n')
            f.write('\t\ttranslate<0,0,1>*paksize*int_y/2\n')
            f.write('\t\ttranslate<1,0,0>*paksize*int_x/2\n')
            f.write('\t}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-1)/4\n')
            f.write('\t}\n')
            f.write('\tobject{\n')
            f.write('\tintersection{object{output_obj\n')
            f.write('\t\trotate<0,270,0>\n')
            f.write('\t\ttranslate<1,0,0>*paksize*int_y/2\n')
            f.write('\t}\n')
            f.write('\tobject{cut_box}}\n')
            f.write('\t\ttranslate<-1,0,1>*paksize*number_width*(-3)/4\n')
            f.write('\t}}\n')
            f.write('\tscale<1,.8165,1> // To set 1 distance of y direction as 1px, rescaling the hight\n')
            f.write('\ttranslate<1,0,1>*paksize*(3)\n')
            f.write('}')
        return
    def make_template(self):
        self.write_snow(self.outfile)
        print("make snow.inc")
        self.write_file(self.outfile)
        print("make "+self.outfile)
        print("make templates successfully")
        return